name: PlasticBullet
options:
  bundleIdPrefix: com.zincTechnologyInc.PlasticBullet
  defaultConfig: Debug
  deploymentTarget:
    iOS: "14.3"
  postGenCommand: echo "DOING IT - postGenCommand"; pod install
packages:
  SwiftyMarkdown:
    url: https://github.com/SimonFairbairn/SwiftyMarkdown
    majorVersion: 1.2.4
  Sentry:
    url: https://github.com/getsentry/sentry-cocoa
    majorVersion: 7.0.0
targets:
  PlasticBullet:
    CFBundleDisplayName: "PlasticBullet"
    CFBundleIconName: Media.xcassets/AppIcon.appiconset
    CFBundleName: PlasticBullet
    type: application
    platform: iOS
    sources:
      - PlasticBullet
    scheme:
      testTargets:
      - name: PlasticBulletTests
        randomExecutionOrder: true
      gatherCoverageData: true
      coverageTargets:
        - PlasticBullet
    settings:
      base:
        INFOPLIST_FILE: PlasticBullet/Info.plist
        SWIFT_OBJC_BRIDGING_HEADER: PlasticBullet/PlasticBullet-Bridging-Header.h
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 5GGD34ZNFU
        ENABLE_BITCODE: NO
        PRODUCT_BUNDLE_IDENTIFIER: com.zincTechnologyInc.PlasticBullet
        SWIFT_VERSION: 5.3
        TARGETED_DEVICE_FAMILY: 1,2
        MARKETING_VERSION: 5.0.0
        CURRENT_PROJECT_VERSION: 0
      configs:
        Debug:
          DEBUG_MODE: YES
        Release:
          DEBUG_MODE: NO
    dependencies:
      - package: SwiftyMarkdown
  PlasticBulletTests:
    type: bundle.unit-test
    platform: iOS
    dependencies:
      - target: PlasticBullet
    sources:
      - path: PlasticBulletTests
  PlasticBulletUITests:
    type: bundle.ui-testing
    platform: iOS
    dependencies:
      - target: PlasticBullet
    sources:
      - path: PlasticBulletUITests